#pragma once

#include <AP_HAL/AP_HAL_Boards.h>

#ifndef AP_OpenMV_TELEM_ENABLED
#define AP_OpenMV_TELEM_ENABLED 1
#endif

#ifndef AP_OpenMV_D_TELEM_ENABLED
#define AP_OpenMV_D_TELEM_ENABLED AP_OpenMV_TELEM_ENABLED
#endif

#ifndef AP_OpenMV_SPORT_TELEM_ENABLED
#define AP_OpenMV_SPORT_TELEM_ENABLED AP_OpenMV_TELEM_ENABLED
#endif

#ifndef AP_OpenMV_SPORT_PASSTHROUGH_ENABLED
#define AP_OpenMV_SPORT_PASSTHROUGH_ENABLED AP_OpenMV_SPORT_TELEM_ENABLED
#endif

#ifndef HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL
#define HAL_WITH_FRSKY_TELEM_BIDIRECTIONAL AP_OpenMV_SPORT_PASSTHROUGH_ENABLED
#endif
